# name=regex ; replacement is derived automatically as <name>
telegram-token=\b\d{9,10}:[A-Za-z0-9_-]{30,}\b
github-token=\bgh[pousr]_[A-Za-z0-9]{36,}\b
openai-key=\bsk-[A-Za-z0-9]{20,}T3BlbkFJ[A-Za-z0-9]{20,}\b
gitlab-token=\bglpat-[A-Za-z0-9\-_]{20,}\b
slack-token=\bxox[baprs]-[A-Za-z0-9\-]{10,}\b
gcp-api-key=\bAIza[A-Za-z0-9\-_]{35}\b
aws-access-key=\bAKIA[A-Z0-9]{16}\b
crt-like-text=(?s)-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----
pem-like-text=(?s)-----BEGIN [A-Z0-9_ -]+-----.*?-----END [A-Z0-9_ -]+-----
hex-like-text=\b(?:[A-Fa-f0-9]{32,})\b
base64-like-text=\b(?:[A-Za-z0-9+/]{48,}={0,2})\b
